const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const env = require('../config/env');

const DEFAULT_QUESTION = "If you could have any superpower, what would it be?";

// In-memory lock to prevent race conditions when both users open chat simultaneously
const generatingMap = new Map();

exports.getIcebreaker = async (req, res) => {
  const { conversationId } = req.query;
  const apiKey = env.GEMINI_API_KEY;

  if (!apiKey || apiKey === "your_gemini_api_key_here") {
    return res.json({ question: DEFAULT_QUESTION });
  }

  if (!conversationId) {
    // Fallback if no conversation
    return res.json({ question: DEFAULT_QUESTION });
  }

  // Check if this conversation's icebreaker is ALREADY being generated by another concurrent request
  if (generatingMap.has(conversationId)) {
    try {
      const question = await generatingMap.get(conversationId);
      return res.json({ question });
    } catch (e) {
      return res.json({ question: DEFAULT_QUESTION });
    }
  }

  // Create the generation promise
  const generationPromise = (async () => {
    let prompt = "";
    try {
      const conversation = await prisma.conversation.findUnique({
        where: { id: conversationId },
        include: {
          participants: {
            include: { user: true }
          }
        }
      });

      if (conversation) {
        if (conversation.icebreaker) {
          return conversation.icebreaker;
        }

        if (conversation.participants.length >= 2) {
          const u1 = conversation.participants[0].user;
          const u2 = conversation.participants[1].user;
          const h1 = u1.hobbies || "not specified";
          const h2 = u2.hobbies || "not specified";

          prompt = `Generate a single short icebreaker question for two users about to start a chat.
User 1 Hobbies: ${h1}
User 2 Hobbies: ${h2}
Instructions:
1. Examine the hobbies for any overlapping interests. If found, ask a direct question about that shared interest.
2. If no overlap, create a question that playfully bridges their different hobbies.
3. Keep it to 1-2 sentences. 
4. Be engaging and friendly.
5. Only return the question itself, no preamble or extra text.`;
        } else {
          return DEFAULT_QUESTION;
        }
      } else {
        return DEFAULT_QUESTION;
      }
    } catch (e) {
      console.error('Error fetching users for icebreaker:', e);
      return DEFAULT_QUESTION;
    }

    try {
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }]
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('Gemini API 400 error body:', errorText);
        throw new Error(`Gemini API error: ${response.status}`);
      }

      const data = await response.json();
      const question = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || DEFAULT_QUESTION;

      try {
        await prisma.conversation.update({
          where: { id: conversationId },
          data: { icebreaker: question }
        });
      } catch (err) {
        console.error('Failed to save icebreaker to DB:', err);
      }

      return question;
    } catch (error) {
      console.error('Icebreaker generation error:', error);
      return DEFAULT_QUESTION;
    }
  })();

  // Store promise in the map
  generatingMap.set(conversationId, generationPromise);

  try {
    const question = await generationPromise;
    // Remove from map once done since it's saved to DB now
    generatingMap.delete(conversationId);
    return res.json({ question });
  } catch (error) {
    generatingMap.delete(conversationId);
    return res.json({ question: DEFAULT_QUESTION });
  }
};
